		<option value="">Select City</option>
		<option>BAGERHAT</option>
		<option>BANDARBAN</option>
		<option>BARISHAL</option>
		<option>BOGRA</option>
		<option>BORGUNA</option>
		<option>BRAHMANBARIA</option>
		<option>CHANDPUR</option>
		<option>CHAPAINAWABGANJ</option>
		<option>CHITTAGONG</option>
		<option>CHUADANGA</option>
		<option>COMILLA</option>
		<option>COX''SBAZAR</option>
		<option>DHAKA</option>
		<option>DINAJPUR</option>
		<option>FARIDPUR</option>
		<option>FENI</option>
		<option>GAIBANDHA</option>
		<option>GAZIPUR</option>
		<option>GOPALGANJ</option>
		<option>HOBIGANJ</option>
		<option>JAMALPUR</option>
		<option>JESSORE</option>
		<option>JHALOKHATHI</option>
		<option>JHINAIDAH</option>
		<option>JOYPURHAT</option>
		<option>KHAGRACHHORI</option>
		<option>KHULNA</option>
		<option>KISHOREGANJ</option>
		<option>KURIGRAM</option>
		<option>KUSTIA</option>
		<option>LAKKHIPUR</option>
		<option>LALMONIRHAT</option>
		<option>MADARIPUR</option>
		<option>MAGURA</option>
		<option>MANIKGANJ</option>
		<option>MEHERPUR</option>
		<option>MOULOVIBAZAR</option>
		<option>MUNSHIGANJ</option>
		<option>MYMENSHING</option>
		<option>NAOGAON</option>
		<option>NARAYANGANJ</option>
		<option>NATORE</option>
		<option>NETROKONA</option>
		<option>NILPHAMARI</option>
		<option>NOAKHALI</option>
		<option>NORAIL</option>
		<option>NORSHINGDI</option>
		<option>PABNA</option>
		<option>PIROZPUR</option>
		<option>PONCHAGARH</option>
		<option>POTUAKHALI</option>
		<option>RAJBARI</option>
		<option>RAJSHAHI</option>
		<option>RANGAMATI</option>
		<option>RANGPUR</option>
		<option>SATKHIRA</option>
		<option>SHARIATPUR</option>
		<option>SHERPUR</option>
		<option>SIRAJGANJ</option>
		<option>SUNAMGANJ</option>
		<option>SYLHET</option>
		<option>TANGAIL</option>
		<option>THAKUGAON</option>
		<option>VOLA</option>
		


